export default {
    "hosts" : {
        "domain" : "alpha.jitsi.net",
        "muc" : "conference.alpha.jitsi.net",
        "focus" : "focus.alpha.jitsi.net"
    },
    "disableSimulcast" : false,
    "enableRemb" : false,
    "enableTcc" : true,
    "resolution" : 720,
    "constraints" : {
        "video" : {
            "aspectRatio" : 1.7777777777777777,
            "height" : { "ideal" : 720, "max" : 720, "min" : 180 },
            "width" : { "ideal" : 1280, "max" : 1280, "min" : 320 }
        }
    },
    "analytics" : {},
    "p2pStunServers" : [ { "urls" : "stun:stun.l.google.com:19302" }, { "urls" : "stun:stun1.l.google.com:19302" }, { "urls" : "stun:stun2.l.google.com:19302" } ],
    "p2p" : {
        "enabled" : false,
        "preferH264" : true,
        "disableH264" : true,
        "useStunTurn" : true,
        "stunServers" : [ { "urls" : "stun:stun.l.google.com:19302" }, { "urls" : "stun:stun1.l.google.com:19302" }, { "urls" : "stun:stun2.l.google.com:19302" } ]
    },
    "useStunTurn" : true,
    "useIPv6" : false,
    "useNicks" : false,
    "clientNode" : "http://jitsi.org/jitsimeet",
    "desktopSharing" : "ext",
    "chromeExtensionId" : "pgplkhlodppdcflanmijbnpgpjkegfgc",
    "desktopSharingSources" : [ "screen", "window" ],
    "desktopSharingChromeExtId" : "pgplkhlodppdcflanmijbnpgpjkegfgc",
    "desktopSharingChromeDisabled" : false,
    "desktopSharingChromeSources" : [ "screen", "window", "tab" ],
    "desktopSharingChromeMinExtVersion" : "0.1.3",
    "desktopSharingFirefoxExtId" : "jidesha@alpha.jitsi.net",
    "desktopSharingFirefoxDisabled" : true,
    "desktopSharingFirefoxMaxVersionExtRequired" : "0",
    "desktopSharingFirefoxExtensionURL" : "",
    "useRoomAsSharedDocumentName" : false,
    "enableLipSync" : false,
    "disableRtx" : false,
    "enableRtpStats" : false,
    "enableStatsID" : true,
    "openBridgeChannel" : "websocket",
    "channelLastN" : -1,
    "minHDHeight" : 540,
    "startBitrate" : "800",
    "disableAudioLevels" : false,
    "useRtcpMux" : true,
    "useBundle" : true,
    "disableSuspendVideo" : true,
    "stereo" : true,
    "forceJVB121Ratio" : -1,
    "enableTalkWhileMuted" : true,
    "hiddenDomain" : "recorder.alpha.jitsi.net",
    "transcribingEnabled" : false,
    "enableRecording" : true,
    "liveStreamingEnabled" : true,
    "fileRecordingsEnabled" : false,
    "fileRecordingsServiceEnabled" : false,
    "fileRecordingsServiceSharingEnabled" : false,
    "requireDisplayName" : false,
    "recordingType" : "jibri",
    "enableWelcomePage" : true,
    "isBrand" : false,
    "logStats" : false,
    "callStatsID" : "294674397",
    "callStatsSecret" : "9IJJTtOdheZs:MHov7tz0Gc3h/6NYXiNVCqA1tpTmKPH0AdXTYtAKVRY=",
    "dialInNumbersUrl" : "https://api.jitsi.net/phoneNumberList",
    "dialInConfCodeUrl" : "https://api.jitsi.net/conferenceMapper",
    "dialOutCodesUrl" : "https://api.jitsi.net/countrycodes",
    "dialOutAuthUrl" : "https://api.jitsi.net/authorizephone",
    "peopleSearchUrl" : "https://api.jitsi.net/directorySearch",
    "inviteServiceUrl" : "https://api.jitsi.net/conferenceInvite",
    "inviteServiceCallFlowsUrl" : "https://api.jitsi.net/conferenceinvitecallflows",
    "peopleSearchQueryTypes" : [ "user", "conferenceRooms" ],
    "startAudioMuted" : 9,
    "startVideoMuted" : 9,
    "prejoinPageEnabled" : true,
    "enableUserRolesBasedOnToken" : false,
    "hepopAnalyticsUrl" : "",
    "hepopAnalyticsEvent" : {
        "product" : "lib-jitsi-meet",
        "subproduct" : "alpha",
        "name" : "jitsi.page.load.failed",
        "action" : "page.load.failed",
        "actionSubject" : "page.load",
        "type" : "page.load.failed",
        "source" : "page.load",
        "attributes" : { "type" : "operational", "source" : "page.load" },
        "server" : "alpha.jitsi.net"
    },
    "deploymentInfo" : {
        "environment" : "alpha",
        "envType" : "dev",
        "releaseNumber" : "",
        "shard" : "all",
        "region" : "us-west-2",
        "userRegion" : "",
        "crossRegion" : 0
    },
    "rttMonitor" : {
        "enabled" : false,
        "initialDelay" : 30000,
        "getStatsInterval" : 10000,
        "analyticsInterval" : 60000,
        "stunServers" : {
            "ap-se-1" : "all-ap-se-1-turn.jitsi.net:443",
            "ap-se-2" : "all-ap-se-2-turn.jitsi.net:443",
            "eu-central-1" : "all-eu-central-1-turn.jitsi.net:443",
            "eu-west-1" : "all-eu-west-1-turn.jitsi.net:443",
            "us-east-1" : "all-us-east-1-turn.jitsi.net:443",
            "us-west-2" : "all-us-west-2-turn.jitsi.net:443"
        }
    },
    "abTesting" : {},
    "testing" : { "octo" : { "probability" : 0 } }
}